### ISSUE TITLE
Sass has HSV support, though it's listed as missing it

### ISSUE THREAD

**Issue by TheJaredWilcurt** [futekov/csspre#43]
http://sass-lang.com/documentation/Sass/Script/Functions.html#hsl_functions

```scss
hue($color)
saturation($color)
lightness($color)
```

**Comment by futekov** [comment]
The table lists that Sass **has** HSL support, but not HSV/HSB, which is different.

**Comment by TheJaredWilcurt** [comment]
yep, your'e right:

https://en.wikipedia.org/wiki/HSL_and_HSV
